coffeestats/caffeine/urls.py
# -*- python -*-

from django.urls import re_path

from .views import (
    AboutView,
    CaffeineActivationView,
    CaffeineRegistrationView,
    ConfirmActionView,
    DeleteAccountView,
    DeleteCaffeineView,
    ExploreView,
    ExportActivityView,
    ImprintView,
    IndexView,
    OnTheRunOldView,
    OnTheRunView,
    OverallView,
    ProfileView,
    PublicProfileView,
    RegistrationClosedView,
    SelectTimeZoneView,
    SettingsView,
    SubmitCaffeineOnTheRunView,
    SubmitCaffeineView,
    random_users,
)

urlpatterns = [
    re_path(r"^$", IndexView.as_view(), name="home"),
    # django_registration
    re_path(
        r"^auth/activate/(?P<activation_key>[-:\w]+)/$",
        CaffeineActivationView.as_view(),
        name="django_registration_activate",
    ),
    re_path(
        r"^auth/register/$",
        CaffeineRegistrationView.as_view(),
        name="django_registration_register",
    ),
    re_path(
        r"^auth/register/closed$",
        RegistrationClosedView.as_view(),
        name="django_registration_disallowed",
    ),
    re_path(r"^about/$", AboutView.as_view(), name="about"),
    re_path(r"^explore/$", ExploreView.as_view(), name="explore"),
    re_path(r"^imprint/$", ImprintView.as_view(), name="imprint"),
    re_path(r"^overall/$", OverallView.as_view(), name="overall"),
    re_path(r"^settings/$", SettingsView.as_view(), name="settings"),
    re_path(r"^selecttimezone/$", SelectTimeZoneView.as_view(), name="select_timezone"),
    re_path(r"^ontherun/$", OnTheRunOldView.as_view(), name="ontherunold"),
    re_path(
        r"^ontherun/(?P<username>[\w0-9@.+-_]+)/(?P<token>\w+)/$",
        OnTheRunView.as_view(),
        name="ontherun",
    ),
    re_path(
        r"^activity/export/$", ExportActivityView.as_view(), name="export_activity"
    ),
    re_path(r"^deletemyaccount/$", DeleteAccountView.as_view(), name="delete_account"),
    re_path(
        r"^(?P<drink>(coffee|mate))/submit/$",
        SubmitCaffeineView.as_view(),
        name="submit_caffeine",
    ),
    re_path(
        r"^(?P<drink>(coffee|mate))/submit/(?P<username>[\w0-9@.+-_]+)"
        r"/(?P<token>\w+)/$",
        SubmitCaffeineOnTheRunView.as_view(),
        name="submit_caffeine_otr",
    ),
    re_path(
        r"^action/confirm/(?P<code>\w+)/$",
        ConfirmActionView.as_view(),
        name="confirm_action",
    ),
    re_path(
        r"^delete/(?P<pk>\d+)/$", DeleteCaffeineView.as_view(), name="delete_caffeine"
    ),
    re_path(r"^profile/$", ProfileView.as_view(), name="profile"),
    re_path(
        r"^profile/(?P<username>[\w0-9@.+-_]+)/$",
        PublicProfileView.as_view(),
        name="public",
    ),
    re_path(r"^random-users$", random_users, name="random_users"),
]

coffeestats/caffeine/forms.py
"""
Forms for coffeestats.

"""

from datetime import datetime

from django import forms
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_registration.forms import RegistrationFormUniqueEmail

from .models import ACTION_TYPES, Action, Caffeine, User

DUPLICATE_USER_ERROR = _("A user with that username already exists.")
DUPLICATE_EMAIL_ERROR = _(
    "This email address is already in use. " "Please supply a different email address."
)
PASSWORD_MISMATCH_ERROR = _("Passwords must match!")
INVALID_TIMEZONE_ERROR = _("Invalid time zone name")
EMPTY_TIMEZONE_ERROR = _("Time zone must not be empty.")


class CoffeestatsRegistrationForm(RegistrationFormUniqueEmail):
    """
    This is the form for registering new users.

    """

    firstname = forms.CharField(label=_("First name"), required=False)
    lastname = forms.CharField(label=_("Last name"), required=False)
    location = forms.CharField(label=_("Location"), required=False)

    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.

        """
        existing = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if existing.exists():
            raise forms.ValidationError(DUPLICATE_USER_ERROR)
        else:
            return self.cleaned_data["username"]

    class Meta(RegistrationFormUniqueEmail.Meta):
        model = User


class SettingsForm(forms.ModelForm):
    """
    This is the form for changing a user's settings.

    """

    password1 = forms.CharField(required=False)
    password2 = forms.CharField(required=False)
    password_set = False
    email_action = None

    class Meta:
        model = User
        fields = ["email", "first_name", "last_name", "location"]

    def clean_password2(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if (password2 or password1) and password1 != password2:
            raise forms.ValidationError(PASSWORD_MISMATCH_ERROR)
        return password2

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        emailuser = User.objects.filter(
            email__iexact=self.cleaned_data["email"]
        ).first()
        if emailuser is not None and emailuser != self.instance:
            raise forms.ValidationError(DUPLICATE_EMAIL_ERROR)
        if self.cleaned_data["email"] != self.instance.email:
            self.email_action = Action.objects.create_action(
                self.instance,
                ACTION_TYPES.change_email,
                self.cleaned_data["email"],
                settings.EMAIL_CHANGE_ACTION_VALIDITY,
            )
            self.cleaned_data["email"] = self.instance.email
        return self.cleaned_data["email"]

    def clean(self):
        cleaned_data = super(SettingsForm, self).clean()
        if "password2" in self.cleaned_data and self.cleaned_data["password2"]:
            self.password_set = True
            self.instance.set_password(self.cleaned_data["password2"])
        return cleaned_data


class SelectTimeZoneForm(forms.ModelForm):
    """
    This is the form for selecting a user's time zone.

    """

    class Meta:
        model = User
        fields = ["timezone"]
        error_messages = {
            "timezone": {
                "required": EMPTY_TIMEZONE_ERROR,
            },
        }

    def __init__(self, *args, **kwargs):
        super(SelectTimeZoneForm, self).__init__(*args, **kwargs)
        self.fields["timezone"].required = True

    def clean_timezone(self):
        cleantimezone = self.cleaned_data["timezone"]
        try:
            with timezone.override(cleantimezone):
                return cleantimezone
        except:
            raise forms.ValidationError(INVALID_TIMEZONE_ERROR)


class SubmitCaffeineForm(forms.ModelForm):
    """
    This is the form for new caffeine submissions.

    """

    date = forms.DateField(required=False)
    time = forms.TimeField(required=False)

    class Meta:
        model = Caffeine
        fields = []

    def __init__(self, user, ctype, *args, **kwargs):
        super(SubmitCaffeineForm, self).__init__(*args, **kwargs)
        self.instance.ctype = ctype
        self.instance.user = user
        self.instance.timezone = user.timezone

    def clean(self):
        if self.cleaned_data["date"] is None or self.cleaned_data["time"] is None:
            servertz = timezone.get_default_timezone()
            with timezone.override(self.instance.timezone):
                usertz = timezone.get_current_timezone()
                self.instance.date = timezone.make_naive(
                    timezone.localtime(
                        timezone.make_aware(timezone.now(), servertz), usertz
                    ),
                    usertz,
                )
        else:
            self.instance.date = datetime.combine(
                self.cleaned_data["date"], self.cleaned_data["time"]
            )
        return super(SubmitCaffeineForm, self).clean()

coffeestats/templates/about.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="white-box">
  <h2>{% trans "About coffeestats.org" %}</h2>
  <p>{% blocktrans %}Coffeestats.org was written with the help of two Mac OS X systems, a Debian GNU/Linux system and is proudly running on <a href="http://www.debian.org/">Debian GNU/Linux</a>. We want to thank the awesome Free Software community for all their software and art available under free licenses:{% endblocktrans %}</p>
  <ul>
    <li>{% blocktrans %}<a href="http://chartjs.org/">Chart.js</a> by Nick Downie{% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="https://github.com/adobe/source-sans-pro">Source Sans Pro</a> by Adobe{% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://www.fontsquirrel.com/fonts/amaranth">Amaranth</a> by Gesine Todt{% endblocktrans %}</li>
    <li>{% blocktrans %}Iconset by <a href="http://www.flaticon.com/">flaticon.com</a> {% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://vervex.deviantart.com/art/Somacro-32-300DPI-Social-Media-Icons-267955425">Somacro Social Media Icons</a> by <a href="http://veodesign.com">Vervex</a>{% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://picjumbo.com/girl-with-watches-typing-on-macbook/">Backgroundimage Landingpage</a> by <a href="https://twitter.com/viktorhanacek">Viktor Hanacek</a>{% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://picjumbo.com/cafe-workspace-with-diary/">Backgroundimage Profilepage</a> by <a href="http://inspirationfeed.com">inspirationfeed.com</a>{% endblocktrans %}</li>
  </ul>
</div>
<div class="white-box">
  <h2>{% trans "Changelog" %}</h2>
  <ul>
    <li>{% trans "2024-05-15 Update dependencies, remove broken social links, remove unused OAuth2 code" %}</li>
    <li>{% trans "2018-05-20 Remove piwik integration" %}</li>
    <li>{% trans "2016-09-16 Update to Django 1.9.9 and latest versions of other Dependencies" %}"</li>
    <li>{% trans "2016-01-16 Update to Django 1.9 and latest versions of other Dependencies" %}</li>
    <li>{% blocktrans %}2014-06-20 reimplementation in <a href="http://www.djangoproject.com/">Django</a>, new design by Jeremias{% endblocktrans %}</li>
    <li>{% trans "2014-02-20 REST API for adding drinks by Clemens" %}</li>
    <li>{% trans "2013-05-23 New design by Jeremias" %}</li>
    <li>{% trans "2013-05-07 Added nice social media icons to profile page" %}</li>
    <li>{% trans "2013-05-03 Public URL has changed (update your bookmarks!)" %}</li>
    <li>{% trans "2013-04-28 Performance and security improvments" %}</li>
    <li>{% trans "2013-03-23 New update page" %}</li>
    <li>{% trans "2013-03-23 Using Chart.js for Graphs!" %}</li>
    <li>{% trans "2013-03-23 Added Mate to drinks" %}</li>
    <li>{% trans "2013-02-15 Added more Ranking stuff onto the explore page" %}</li>
    <li>{% trans "2013-02-27 Some bugfixes for OTR" %}</li>
    <li>{% trans "2013-02-15 Max email length resized up to 50 chars" %}</li>
    <li>{% trans "2013-02-15 Made time for coffee +1 with js not servertime. Better feeling for users who not live in GMT+1" %}</li>
    <li>{% trans "2013-02-13 Added some awesome icons to navigation and cleaned up interface" %}</li>
    <li>{% blocktrans %}2012-02-11 Added SSL <a href="https://coffeestats.org/">https://coffeestats.org/</a>{% endblocktrans %}</li>
    <li>{% trans "2012-11-06 Migrated from Debian Squeeze to OpenBSD" %}</li>
    <li>{% trans "2012-02-11 Added on-the-run Mode" %}</li>
    <li>{% trans "2012-01-23 Added Overall Stats" %}</li>
  </ul>
</div>
<div class="white-box">
  <h2>{% trans "Credits" %}</h2>
  <p>{% trans "Some awesome guys have been involved in growing up coffeestats.org so far." %}</p>
  <ul>
    <li>{% blocktrans %}<a href="http://github.com/neverpanic">Clemens Lang</a> (implementing add-drink REST API){% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://www.art-ifact.de/">Jeremias Arnstadt</a> (new design){% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://dittberner.info/">Jan Dittberner</a> (massive code improvements in many cases, port to Django){% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://sotiriu.de/">Nikolas Sotiriu</a> (testing the site for security flaws){% endblocktrans %}</li>
    <li>{% blocktrans %}<a href="http://noqqe.org/">Florian Baumann</a> (project founder, source of inspiration, hosting until 2014-06-20){% endblocktrans %}</li>
  </ul>
</div>
<div class="white-box">
  <h2>{% trans "Contribution" %}</h2>
  <p>{% blocktrans %}coffeestats.org is OpenSource. Feel free to <a href="https://github.com/coffeestats/coffeestats-django">contribute code</a>,
    <a href="https://github.com/coffeestats/coffeestats-django/issues">share your ideas or report bugs</a>!{% endblocktrans %}</p>
  <p>{% blocktrans %}Development / deployment documentation is at <a href="https://coffeestats.readthedocs.org">coffeestats.readthedocs.org</a>{% endblocktrans %}</p>
  <p>{% blocktrans %}Or show some love &lt;3{% endblocktrans %}</p>
</div>
{% endblock content %}

coffeestats/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="author" content="F. Baumann, H. Winter, J. Dittberner"/>
    <meta name="description" content="{% trans "coffeestats.org | All about coffee" %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}coffeestats.org{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>

    <!-- This file store project specific CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "css/caffeine.css" %}"/>

    <!-- Favicons and touch icons for mobile devices -->
    <link rel="shortcut icon" href="{{ ABSOLUTE_ROOT }}{% static "images/favicon.png" %}"/>
    <link rel="apple-touch-icon" href="{{ ABSOLUTE_ROOT }}{% static "images/touch-icon-57.png" %}"/>
    <link rel="apple-touch-icon" sizes="72x72" href="{{ ABSOLUTE_ROOT }}{% static "images/touch-icon-77.png" %}"/>
    <link rel="apple-touch-icon" sizes="114x114" href="{{ ABSOLUTE_ROOT }}{% static "images/touch-icon-114.png" %}"/>
    <link rel="apple-touch-icon" sizes="144x144" href="{{ ABSOLUTE_ROOT }}{% static "images/touch-icon-144.png" %}"/>

    <!-- Use this to quickly test CSS changes in a template,
        then move to caffeine.css -->
    {% block extra_css %}{% endblock extra_css %}
</head>

<body class="{{ request.resolver_match.url_name }}">
<ul class="flash-messages" id="system-flash">{% spaceless %}
    {% if messages %}
        {% for message in messages %}
            {% if 'registerdrink' not in message.tags %}
                <li class="{{ message.tags }}">{{ message }} <a href="#" class="close">X</a></li>{% endif %}
        {% endfor %}
    {% endif %}
    {% block extra_system_flash %}{% endblock extra_system_flash %}
{% endspaceless %}</ul>
<div id="wrapper">
    <div id="header">
        <div class="headerWrapper">
            {% block loginnav %}
                {% if user.is_authenticated %}
                    <nav class="right mainNav">
                        <ul>{% spaceless %}
                            {% for item in navitems %}
                                <li{% if item.is_active %} class="active"{% endif %}>
                                    {% if not item.children %}
                                        <a href="{{ item.url }}" class="{{ item.css_class }}">{{ item.title }}</a>
                                    {% else %}
                                        <span class="{{ item.css_class }}"><span>{{ item.title }}</span></span>
                                        <ul class="subNav {{ item.children_css_class }}">
                                            {% for child_item in item.children %}
                                                <li>{% if child_item.nav_type == "submit" %}
                                                    <form action="{{ child_item.url }}" method="post">
                                                        {% csrf_token %}
                                                        <input type="submit" value="{{ child_item.title }}"
                                                               class="{{ child_item.css_class }}"/>
                                                    </form>
                                                {% else %}
                                                    <a href="{{ child_item.url }}" class="{{ child_item.css_class }}"
                                                            {% if child_item.rel %}
                                                       rel="{{ child_item.rel }}"{% endif %}>{{ child_item.title }}</a>
                                                {% endif %}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        {% endspaceless %}</ul>
                    </nav>
                    <nav class="right mainNavMobile">
                        <ul>{% spaceless %}
                            <li class="menuIndicator">
                                <span class="icon coffeestats-menu"><span>Show Navigation</span></span>
                                <ul>
                                    {% for item in navitems %}
                                        <li{% if item.is_active %} class="active"{% endif %}>
                                            {% if not item.children %}
                                                <a href="{{ item.url }}"
                                                   class="{{ item.css_class }}">{{ item.title }}</a>
                                            {% endif %}
                                        </li>
                                        {% for itemchild in item.children %}
                                            <li><a href="{{ itemchild.url }}"
                                                   class="{{ itemchild.css_class }}">{{ itemchild.title }}</a></li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endspaceless %}</ul>
                    </nav>
                {% else %}
                    <nav class="right login">
                        <ul>
                            <li>
                                <span>{% trans "Login" %}</span>
                                <ul class="loginBox">
                                    <li>
                                        <form action="{% url "auth_login" %}" method="post" class="inlineform"
                                              id="login">
                                            {% csrf_token %}
                                            {{ form.username.errors }}
                                            {{ form.password.errors }}
                                            <input type="text" required pattern="[a-z][a-z0-9_-]{1,29}" name="username"
                                                   id="id_login_username"
                                                   {% if form.username.value %}value="{{ form.username.value }}" {% endif %}>
                                            <label for="username" alt="{% trans "Username" %}"
                                                   placeholder="{% trans "Username" %}"></label>
                                            <input type="password" required name="password" id="id_login_password"/>
                                            <label for="password" alt="{% trans "Password" %}"
                                                   placeholder="{% trans "Password" %}"></label>
                                            {% url "auth_password_reset" as passwordreset_url %}
                                            {% blocktrans %}<a href="{{ passwordreset_url }}" class="right">Forgot your
                                                password?</a>{% endblocktrans %}
                                            <input type="submit" name="submit" value="{% trans "Login" %}"/>
                                            {% url 'home' as home_url %}
                                            <input type="hidden" name="next" value="{% if request.GET.next == home_url or not request.GET.next %}{% url 'profile' %}{% else %}{{ request.GET.next }}{% endif %}"/>
                                        </form>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="{% url "django_registration_register" %}"
                                   class="btn">{% trans "Register" %}</a></li>
                        </ul>
                    </nav>
                {% endif %}
            {% endblock loginnav %}
            <h1><a href="{% url 'home' %}"
                   title="{% trans '... about what keeps you awake at night' %}">coffeestats.org</a></h1>
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div class="footer">
        {% url "imprint" as imprinturl %}
        <p class="footertext">{% blocktrans %}<a href="/">coffeestats.org</a> is a project by
            <a href="https://jan.dittberner.info/">Jan Dittberner</a>,
            <a href="http://www.art-ifact.de/">Jeremias Arnstadt</a> &amp;
            <a href="http://noqqe.de/">Florian Baumann</a>.
            See <a href="{{ imprinturl }}">Imprint</a>.{% endblocktrans %}</p>
    </div>
</div>
<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery.equalheights.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/scripts.js" %}"></script>
<script type="text/javascript">
    /* global $ */
    $(document).ready(function () {
        $('.flash-info').delay(4000).fadeOut(1000, function () {
            this.remove();
        });
        $('.flash-success').delay(4000).fadeOut(1000, function () {
            this.remove();
        });
        $('li a.67se').click(function (event) {
            $(this).parent().fadeOut(1000, function () {
                this.remove();
            });
        });
    });
</script>
{% block extra_js %}{% endblock extra_js %}
</body>
</html>

coffeestats/templates/ontherun.html
{% extends "base.html" %}
{% load i18n static caffeine %}
{% block content %}
<div class="white-box fullWidth">
  <h2>{% trans "On the run?" %}</h2>
  <center>
  {% if messages|messagetags:'registerdrink' %}
  <ul class="flash-messages" id="registerdrink-flash">{% spaceless %}
    {% for message in messages|messagetags:'registerdrink' %}
    <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  {% endspaceless %}</ul>
  {% endif %}
  {% spaceless %}
  <form action="{% url "submit_caffeine_otr" "coffee" username token %}" method="post" id="coffeeform" class="otrblockform">
    <input type="submit" value="{% trans "Coffee!" %}" /><br />
    <input type="hidden" id="id_coffeedate" name="date" />
    <input type="hidden" id="id_coffeetime" name="time" />
    {% csrf_token %}
  </form>
  <form action="{% url "submit_caffeine_otr" "mate" username token %}" method="post" id="mateform" class="otrblockform">
    <input type="submit" value="{% trans "Mate!" %}" /><br />
    <input type="hidden" id="id_matedate" name="date" />
    <input type="hidden" id="id_matetime" name="time" />
    {% csrf_token %}
  </form>
  {% endspaceless %}
  </center>
</div>
{% endblock content %}
{% block extra_js %}
<script type="text/javascript" src="{% url "jsi18n_catalog" packages='caffeine' %}"></script>
<script type="text/javascript" src="{% static "caffeine/js/validation.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#coffeeform').submit(function(event) {
        return sanitize_datetime('input#id_coffeedate', 'input#id_coffeetime');
    });
    $('#mateform').submit(function(event) {
        return sanitize_datetime('input#id_matedate', 'input#id_matetime');
    });
});
</script>
{% endblock extra_js %}

coffeestats/templates/settings.html
{% extends "base.html" %}
{% load i18n static %}
{% if form.non_field_errors %}
    {% block extra_system_flash %}
        {% for message in form.non_field_errors %}
            <li class="flash-error">{{ message }} <a href="#" class="close">X</a></li>
        {% endfor %}
    {% endblock %}
{% endif %}
{% block content %}
    <div class="white-box">
        <h2>{% trans "Update your profile" %}</h2>
        <p>{% trans "You may change your personal information." %}</p>
        <form action="{% url "settings" %}" method="post" class="coffeeform">
            <div class="leftform">
                <h3>{% trans "General" %}</h3>
                <input type="text" name="username" id="id_username" maxlength="30" value="{{ request.user.username }}"
                       readonly="readonly"/>
                {{ form.password1.errors }}
                <input type="password" name="password1" pattern=".{8,}" id="id_password1" maxlength="20" autofocus/>
                <label alt="{% trans "Password" %}" placeholder="{% trans "Password" %}"></label>
                {{ form.password2.errors }}
                <input type="password" name="password2" pattern=".{8,}" id="id_password2"/>
                <label alt="{% trans "Password (again)" %}" placeholder="{% trans "Password (again)" %}"></label>
            </div>
            <div class="leftform">
                <h3>{% trans "Additional" %}</h3>
                {{ form.first_name.errors }}
                <input type="text" name="first_name" id="id_first_name" maxlength="20"
                       {% if form.first_name.value %}value="{{ form.first_name.value }}" {% endif %}/>
                <label alt="{% trans "First name" %}" placeholder="{% trans "First name" %}"></label>
                {{ form.last_name.errors }}
                <input type="text" name="last_name" id="id_last_name" maxlength="20"
                       {% if form.last_name.value %}value="{{ form.last_name.value }}" {% endif %}/>
                <label alt="{% trans "Last name" %}" placeholder="{% trans "Last name" %}"></label>
                {{ form.location.errors }}
                <input type="text" name="location" id="id_location" maxlength="20" placeholder="{% trans "Location" %}"
                       {% if form.location.value %}value="{{ form.location.value }}" {% endif %}/>
                <label alt="{% trans "Location" %}" placeholder="{% trans "Location" %}"></label>
            </div>
            <div class="clear">
                {{ form.email.errors }}
                <input type="email" name="email" pattern="[A-Za-z0-9._%+-]+@[^@]+" required id="id_email"
                       maxlength="128" value="{{ form.email.value }}"/>
                <label alt="{% trans "Email" %}" placeholder="{% trans "Email" %}"></label>
            </div>
            <div class="clearfix"></div>
            <p><input type="submit" name="submit" value="Update my settings"/></p>
            {% csrf_token %}
        </form>
        <div class="clear"></div>
    </div>
    <div class="white-box">
        <h2>{% trans "Export your Activity" %}</h2>
        <p>{% trans "Your data is yours. You will receive the CSV files via email." %}</p>
        <p><a class="btn" href="{% url "export_activity" %}">{% trans "Export, please!" %}</a></p>
    </div>
    <div><!-- space --></div>
    <div class="white-box">
        <h2>{% trans "Delete your data" %}</h2>
        <p>{% trans "Your data is yours. So it is your decission to leave us." %}</p>
        <p><a class="btn" href="{% url "delete_account" %}">{% trans "Delete me, please!" %}</a></p>
    </div>
    <div class="white-box">
        <h2>{% trans "API access" %}</h2>
        <p>{% trans "We have an API that you can use for your own integrations." %}</p>
        <p>{% url "api_usage_agreement" as api_usage_agreement %}{% blocktrans %}
            Please see our
            <a href="{{ api_usage_agreement }}">API usage agreement</a>
            for conditions of the API usage.
        {% endblocktrans %}</p>
        <ul class="list-unstyled">
            <li><a href="{% url "user-list" %}">{% trans "Browse the API" %}</a></li>
        </ul>
    </div>
{% endblock content %}
{% block extra_js %}
    <script type="text/javascript" src="{% url "jsi18n_catalog" packages='caffeine' %}"></script>
    <script type="text/javascript" src="{% static "caffeine/js/validation.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('input#id_password1').bind('invalid', pwfieldvalidation);
            $('input#id_password2').bind('invalid', pwfieldvalidation);
            $('input#id_email').bind('invalid', emailfieldvalidation);

            if (!("autofocus" in document.createElement('input'))) {
                $("input#id_password1").focus();
            }

            $('form').submit(function (event) {
                return sanitize_password(
                                'input#id_password1', 'input#id_password2', true)
                        && sanitize_email('input#id_email')
                        && sanitize_string('input#id_first_name', false,
                                '{% trans "First name" %}')
                        && sanitize_string('input#id_last_name', false,
                                '{% trans "Last name" %}')
                        && sanitize_string('input#id_location', false,
                                '{% trans "Location" %}');
            });
        });
    </script>
{% endblock %}